# ruff: noqa: E501


class StickersEnum:

    KIND_RABBIT = (
        "CAACAgUAAxkBAANcaaHi05BZ_aXpvtoOnOajW5sObW0AAsQUAAIEy4BWAAKN81Nru0Q6BA"
    )
    RABBIT_WITH_CLOCKS = (
        "CAACAgUAAxkBAANaaaHfs0Wp_h4O7bP_aK53qh0zXwIAAoUZAAIDHYBW1wJfjgABv5_qOgQ"
    )
    RABBIT_WITH_CLOCKS_2 = (
        "CAACAgIAAxkBAAOAaaHp_baitUZeIpbvoINK8i4RAAEIAAKniwACojPISFLHAAFsF3B9ljoE"
    )
    SATORU_GOJO = (
        "CAACAgQAAxkBAANeaaHkJfFOuRXvErV1q3hhY7GjiL0AAmwTAAIqZbBRL9XW5aoMtHY6BA"
    )
    CAT_OK = "CAACAgIAAxkBAANgaaHl35MlOypfxvRTQFwpGppBLXoAArKJAAL9jPlKOI48tG9HCgo6BA"
    AMERICAN_PSYCHO = (
        "CAACAgIAAxkBAANiaaHmSpmv76CpzGZF-nuP4ZTJYnIAAuUnAAJZ7NBLasYgxWqW-uU6BA"
    )
    SIYANIE = "CAACAgIAAxkBAANkaaHmZ7qeKzksVyj8rEdvGzY4C80AArIpAAIzOwFJJpskNk8qQ0o6BA"
    YAKUBOVICH = (
        "CAACAgIAAxkBAANmaaHnWoPwWe9IgV0TM9smhPdsd3AAAtVrAAKVqvBKC_yprwH-niQ6BA"
    )
    BILL_MURRAY = (
        "CAACAgIAAxkBAANoaaHnjRQ2F_q_hd0a0orLoqwbme4AAl5sAAIYtPFKvPHlajIbpLs6BA"
    )
    CAT_ZABYL = "CAACAgIAAxkBAANsaaHn7JTUM6Fz5CbEgLQxSbDG-4YAAnaLAAJjRihL_W30VCCkfA86BA"
    SINYAK = "CAACAgIAAxkBAANuaaHoIsM-aQXBcFk8Gd2tEZD46p4AAheUAALn4kFLcu50IZMk5to6BA"
    FISH = "CAACAgIAAxkBAANwaaHoZRlCcPyRwcLy4xWpvVxvyjMAAhUwAALJjklLX_ETAXnIndw6BA"
    DOG_AND_MAN = (
        "CAACAgIAAxkBAANyaaHoiaFbSItan1TWIMAF5ZjXU8IAAh0pAAL7VlFLVeyyRhYEy1g6BA"
    )
    CAT_SHAKE = "CAACAgIAAxkBAAN0aaHotjH7HEJcgM3wjQ3yVfIbK9EAAl4tAAJaJFBLqaA3VTd7jb06BA"
    DOG_NOSE = "CAACAgIAAxkBAAN2aaHo3Z6N8QerX0IIkb_FhF2PhWEAAm4vAAKLnilJu4ty3V8z7wI6BA"
    DOVOLNIY_CAT = (
        "CAACAgIAAxkBAAN4aaHpEmEo-pLJtdFQTfwDthZ7yasAArSKAALAOglJRDQqlBT5VU86BA"
    )
    TINKOFF_OK = (
        "CAACAgIAAxkBAAN6aaHpSifi2M0EPRlmrMRqONVb7nMAAhgdAALiBCBJOmqNbxQaYno6BA"
    )
    TINKOFF_ANGRY = (
        "CAACAgIAAxkBAAN8aaHpcalqk38y-nv8tO-594fEZK4AAi4bAAIvdhlIik7uwYhFqS46BA"
    )

    MARKARYAN_KNIFE = (
        "CAACAgIAAxkBAAN-aaHptlC2OMef4XnYvzMC1tAf0x4AApUXAALbbslJmAGM3g_D3Uo6BA"
    )

    GOSLING = "CAACAgIAAxkBAAOCaaHqbAMKLMDHXTdq8jivxHuS9wcAAqweAAIxeQABS7y1jsruVuIlOgQ"
    DIKAPRIO_OK = (
        "CAACAgIAAxkBAAOEaaHqpR00oc3z2VnWSZSy7TOmHEsAAq4UAAKOJ9BKsRWSJ_runWo6BA"
    )
    BORAT_OK = "CAACAgIAAxkBAAOGaaHq2849IhRBBK7X_uW7rRRWHYMAAjwJAAJ8BQcbq7lvgxkRm-g6BA"
    BODROV_PRIVET = (
        "CAACAgIAAxkBAAOIaaHrNWZXaSOAp1C8BROYaZrJl2IAAjEmAALY2OEAAcwtSTpIZEUvOgQ"
    )
    SLOVO_PASANA = (
        "CAACAgIAAxkBAAOKaaHrmYKW88aydF7T6LEZeuUf66oAAqdBAALDh-FKIIZDtbUKJyE6BA"
    )
    DOG_CASTRULA = (
        "CAACAgIAAxkBAAOMaaHr42wXjpx8pGueWcqNKpTyYwUAAnxkAAKdQyFIi0FsuhkX3E46BA"
    )
    MORGEN_PRIV = (
        "CAACAgIAAxkBAAOOaaHsOejUbmMjEBYCgvb5FKDY0CcAAtUYAALDRSFJPbt6gwimBvk6BA"
    )
    PINGVIN_SPS = (
        "CAACAgIAAxkBAAOQaaHsn1-3EQnqW09iFrhHcsTQHAIAAnQYAAIPMkFKqFHabsx6yU06BA"
    )
    SHELBY = "CAACAgIAAxkBAAOSaaHs9cj5FGob5MzWV_Y9YNBXGL8AArAWAAIOWehLK_OfSpHne2g6BA"
    HOROSHO_SHELBY = (
        "CAACAgIAAxkBAAOWaaHtPPqzkv-E1VmZcIE5AvhGPukAAuQUAAKrfOlL4hIRKoX9zGI6BA"
    )
    LERA_EYES = "CAACAgIAAxkBAAOYaaHtc3N5Qdf3J30ZB_vXX9oSnrkAAi0fAAL7QFlKC0BVjg9Sbx86BA"
    GUD = "CAACAgIAAxkBAAOaaaHtut-fpxsu27NwnRSB8hRqSuwAAjgAA1BXjRBVNuwL86OvnToE"
    KAEF = "CAACAgIAAxkBAAOcaaHtvZMOqWrDD--ZIXeFoOLC1wUAAj0AA1BXjRBR3Icv3JTrcjoE"
    LAIK = "CAACAgIAAxkBAAOeaaHtv1jCDpS_051nldVZ9WHQ9foAAj4AA1BXjRAj1Lv7FSFF8ToE"
    OTETS = "CAACAgIAAxkBAAOgaaHum0lRfEsn-RCGfIFtMJscPfwAAlxvAAKbHfBKsJ58-Pzo7Zs6BA"

    mark_as_done_reply_list = [
        SATORU_GOJO,
        CAT_OK,
        AMERICAN_PSYCHO,
        BILL_MURRAY,
        DOVOLNIY_CAT,
        TINKOFF_OK,
        DIKAPRIO_OK,
        BORAT_OK,
        SLOVO_PASANA,
        PINGVIN_SPS,
        HOROSHO_SHELBY,
        GUD,
        KAEF,
        LAIK,
    ]

    reminders_reply_list = [
        RABBIT_WITH_CLOCKS,
        RABBIT_WITH_CLOCKS_2,
        SIYANIE,
        CAT_ZABYL,
        SINYAK,
        FISH,
        DOG_AND_MAN,
        CAT_SHAKE,
        DOG_NOSE,
        YAKUBOVICH,
        TINKOFF_ANGRY,
        MARKARYAN_KNIFE,
        GOSLING,
        BODROV_PRIVET,
        DOG_CASTRULA,
        MORGEN_PRIV,
        SHELBY,
        LERA_EYES,
        OTETS,
    ]
